In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from pathlib import Path
import hvplot.pandas
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
#read in gdp data
gdp_csv=pd.read_csv(
    Path('GDP.csv')
)

gdp_csv['gdpgrate'] = gdp_csv['GDP'].pct_change(4)
gdp_csv['gdpgrated'] = gdp_csv['gdpgrate'].pct_change()
gdp_csv = gdp_csv.set_index('DATE')
display(gdp_csv.head())
display(gdp_csv.tail())

                GDP  gdpgrate  gdpgrated
DATE
1947-01-01  243.164       NaN        NaN
1947-04-01  245.968       NaN        NaN
1947-07-01  249.585       NaN        NaN
1947-10-01  259.745       NaN        NaN
1948-01-01  265.742  0.092851        NaN

                  GDP  gdpgrate  gdpgrated
DATE
2020-10-01  21477.597 -0.009996  -0.413360
2021-01-01  22038.226  0.025923  -3.593288
2021-04-01  22740.959  0.167554   5.463538
2021-07-01  23202.344  0.097631  -0.417318
2021-10-01  23992.355  0.117087   0.199292

In [5]:
#read in gdp data
cpi_csv=pd.read_csv(
    Path('CPIAUCSL.csv')
)
cpi_csv['cpigrate']=cpi_csv['CPIAUCSL'].pct_change(12)
cpi_csv['cpigrated'] = cpi_csv['CPIAUCSL'].pct_change()
cpi_csv = cpi_csv.set_index("DATE")
display(cpi_csv.head())
display(cpi_csv.tail())

            CPIAUCSL  cpigrate  cpigrated
DATE
1947-01-01     21.48       NaN        NaN
1947-02-01     21.62       NaN   0.006518
1947-03-01     22.00       NaN   0.017576
1947-04-01     22.00       NaN   0.000000
1947-05-01     21.95       NaN  -0.002273

            CPIAUCSL  cpigrate  cpigrated
DATE
2021-09-01   274.214  0.053899   0.004109
2021-10-01   276.590  0.062369   0.008665
2021-11-01   278.524  0.068284   0.006992
2021-12-01   280.126  0.070965   0.005752
2022-01-01   281.933  0.075259   0.006451

In [6]:
econ_data= pd.concat([gdp_csv, cpi_csv], axis=1, join = "inner").dropna()
#econ_data['gdpgratemean'] = econ_data['gdpgrate'].mean()
#econ_data['cpigratemean'] = econ_data['cpigrate'].mean()
econ_data

                  GDP  gdpgrate  gdpgrated  CPIAUCSL  cpigrate  cpigrated
DATE
1948-04-01    272.567  0.108140   0.164664    23.820  0.082727   0.013617
1948-07-01    279.196  0.118641   0.097104    24.400  0.097616   0.010352
1948-10-01    280.366  0.079389  -0.330843    24.310  0.061109  -0.002053
1949-01-01    275.034  0.034966  -0.559560    24.010  0.013936  -0.001663
1949-04-01    271.351 -0.004461  -1.127588    23.920  0.004198   0.000418
...               ...       ...        ...       ...       ...        ...
2020-10-01  21477.597 -0.009996  -0.413360   260.352  0.011842   0.000623
2021-01-01  22038.226  0.025923  -3.593288   262.200  0.013600   0.002432
2021-04-01  22740.959  0.167554   5.463538   266.727  0.041520   0.006411
2021-07-01  23202.344  0.097631  -0.417318   272.184  0.052761   0.004536
2021-10-01  23992.355  0.117087   0.199292   276.590  0.062369   0.008665

[295 rows x 6 columns]

In [7]:
econ_graph = econ_data.hvplot.scatter(
    title='', 
    x='DATE',
    y=['gdpgrate','cpigrate']) 
econ_graph

:NdOverlay   [Variable]
   :Scatter   [DATE]   (value)

In [20]:
for index, row in econ_data.iterrows():
    if (econ_data.loc[index, 'gdpgrated'] < 0 and econ_data.loc[index, 'cpigrated'] < 0):
        econ_data.loc[index, 'stageindex'] = 0
        econ_data.loc[index, 'stage'] = 'Reflation'
    if (econ_data.loc[index, 'gdpgrated'] > 0 and econ_data.loc[index, 'cpigrated'] < 0):
        econ_data.loc[index, 'stageindex'] = 1
        econ_data.loc[index, 'stage'] = 'Recovery'
    if (econ_data.loc[index, 'gdpgrated'] > 0 and econ_data.loc[index, 'cpigrated'] > 0):
        econ_data.loc[index, 'stageindex'] = 2
        econ_data.loc[index, 'stage'] = 'Overheat'
    if (econ_data.loc[index, 'gdpgrated'] < 0 and econ_data.loc[index, 'cpigrated'] > 0):
        econ_data.loc[index, 'stageindex'] = 3
        econ_data.loc[index, 'stage'] = 'Stagflation'

econ_data

,GDP,gdpgrate,gdpgrated,CPIAUCSL,cpigrate,cpigrated,stageindex,stage
DATE,,,,,,,,
1948-04-01,272.567,0.108140,0.164664,23.820,0.082727,0.013617,2,Overheat
1948-07-01,279.196,0.118641,0.097104,24.400,0.097616,0.010352,2,Overheat
1948-10-01,280.366,0.079389,-0.330843,24.310,0.061109,-0.002053,0,Reflation
1949-01-01,275.034,0.034966,-0.559560,24.010,0.013936,-0.001663,0,Reflation
1949-04-01,271.351,-0.004461,-1.127588,23.920,0.004198,0.000418,3,Stagflation
...,...,...,...,...,...,...,...,...
2020-10-01,21477.597,-0.009996,-0.413360,260.352,0.011842,0.000623,3,Stagflation
2021-01-01,22038.226,0.025923,-3.593288,262.200,0.013600,0.002432,3,Stagflation
2021-04-01,22740.959,0.167554,5.463538,266.727,0.041520,0.006411,2,Overheat
2021-07-01,23202.344,0.097631,-0.417318,272.184,0.052761,0.004536,3,Stagflation
2021-10-01,23992.355,0.117087,0.199292,276.590,0.062369,0.008665,2,Overheat

In [21]:
#yahoo finance stock data (for longer timeframe)

#Import data from Yahoo Finance
def stock_df(ticker, start, end):
    stock = yf.Ticker(ticker)
    stock_df = stock.history(start = start, end = end, interval = "1mo")
    return stock_df

start = pd.to_datetime('2010-01-01')
end = pd.to_datetime('today')
                     
#Check Website: https://medium.com/@richardhwlin/how-does-investment-clock-work-c7d8fbbeb7bd

#Import Communication data from Yahoo Finance
IYZ_df = stock_df('IYZ', start, end)
#Import Consumer Discretionary data from Yahoo Finance
IYC_df = stock_df('IYC', start, end)
#Import Consumer Staples data from Yahoo Finance
IYK_df = stock_df('IYK', start, end)
#Import Energy data from Yahoo Finance
IYE_df = stock_df('IYE', start, end)
#Import Financials data from Yahoo Finance
IYF_df = stock_df('IYF', start, end)
#Import HealthCare data from Yahoo Finance
IYH_df = stock_df('IYH', start, end)
#Import Industrials data from Yahoo Finance
IYJ_df = stock_df('IYJ', start, end)
#Import Materials data from Yahoo Finance
IYM_df = stock_df('IYM', start, end)
#Import Real Estate data from Yahoo Finance
IYR_df = stock_df('IYR', start, end)
#Import Technology data from Yahoo Finance
IYW_df = stock_df('IYW', start, end)
#Import Utility data from Yahoo Finance
IDU_df = stock_df('IDU', start, end)
#Import Bond data from Yahoo Finance
AGG_df = stock_df('AGG', start, end)

#Check the lenth of data
display(IYZ_df)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-01-01,14.851826,15.136176,13.284254,13.284254,14508200.0,0.000,0
2010-02-01,13.342583,13.809210,12.890540,13.641515,12023000.0,0.000,0
2010-03-01,13.663386,14.983061,13.663386,14.596638,8751700.0,0.000,0
2010-03-25,NaN,NaN,NaN,NaN,NaN,0.148,0
2010-04-01,14.784787,15.225467,14.755410,14.968404,9913000.0,0.000,0
...,...,...,...,...,...,...,...
2021-12-01,31.052378,33.236218,30.174855,32.817398,19930300.0,0.000,0
2021-12-13,NaN,NaN,NaN,NaN,NaN,0.089,0
2022-01-01,32.900002,33.320000,29.549999,30.930000,20257300.0,0.000,0
2022-02-01,30.660000,31.240000,29.040001,29.080000,8952300.0,0.000,0
2022-02-24,28.520000,29.549999,28.500000,29.490000,799067.0,0.000,0

In [22]:
#Find the daily return of the stock in percentage

# spy_df["Monetary Gain"] = spy_df["Close"].diff()
IYZ_df['Actual Return'] = IYZ_df["Close"].pct_change()
IYC_df['Actual Return'] = IYC_df["Close"].pct_change()
IYK_df['Actual Return'] = IYK_df["Close"].pct_change()
IYE_df['Actual Return'] = IYE_df["Close"].pct_change()
IYF_df['Actual Return'] = IYF_df["Close"].pct_change()
IYH_df['Actual Return'] = IYH_df["Close"].pct_change()
IYJ_df['Actual Return'] = IYJ_df["Close"].pct_change()
IYM_df['Actual Return'] = IYM_df["Close"].pct_change()
IYR_df['Actual Return'] = IYR_df["Close"].pct_change()
IYW_df['Actual Return'] = IYW_df["Close"].pct_change()
IDU_df['Actual Return'] = IDU_df["Close"].pct_change()
AGG_df['Actual Return'] = AGG_df["Close"].pct_change()

In [25]:
IYZ_df.rename(columns = {'Actual Return':'IYZ'}, inplace = True)
IYC_df.rename(columns = {'Actual Return':'IYC'}, inplace = True)
IYK_df.rename(columns = {'Actual Return':'IYK'}, inplace = True)
IYE_df.rename(columns = {'Actual Return':'IYE'}, inplace = True)
IYF_df.rename(columns = {'Actual Return':'IYF'}, inplace = True)
IYH_df.rename(columns = {'Actual Return':'IYH'}, inplace = True)
IYJ_df.rename(columns = {'Actual Return':'IYJ'}, inplace = True)
IYM_df.rename(columns = {'Actual Return':'IYM'}, inplace = True)
IYR_df.rename(columns = {'Actual Return':'IYR'}, inplace = True)
IDU_df.rename(columns = {'Actual Return':'IDU'}, inplace = True)
IYW_df.rename(columns = {'Actual Return':'IYW'}, inplace = True)
AGG_df.rename(columns = {'Actual Return':'AGG'}, inplace = True)

In [33]:
etf_data= pd.concat([IYZ_df['IYZ'],IYC_df['IYC'],IYK_df['IYK'],IYE_df['IYE'],IYF_df['IYF'],IYH_df['IYH'],IYJ_df['IYJ'],IYM_df['IYM'],IYR_df['IYR'],IDU_df['IDU'],IYW_df['IYW'],AGG_df['AGG']], axis=1, join = "inner")

#etf_data=etf_data.set_index("Date")
etf_data

,IYZ,IYC,IYK,IYE,IYF,IYH,IYJ,IYM,IYR,IDU,IYW,AGG
Date,,,,,,,,,,,,
2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-02-01,0.026894,0.047988,0.035277,0.018565,0.031403,0.004051,0.045525,0.075617,0.054570,-0.007139,0.049152,-0.001147
2010-03-01,0.070016,0.073969,0.041490,0.026568,0.085633,0.029174,0.079118,0.079470,0.086900,0.019597,0.060287,-0.000032
2010-04-01,0.025469,0.038758,0.005576,0.046714,0.022185,-0.028221,0.049748,0.008890,0.074242,0.037674,0.021084,0.009742
2010-05-01,-0.038273,-0.057418,-0.061165,-0.117426,-0.090737,-0.071751,-0.091550,-0.089333,-0.056835,-0.058119,-0.074379,0.010932
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-01,-0.033962,-0.011918,-0.021165,-0.048602,-0.053127,-0.036667,-0.046296,-0.021168,-0.024126,-0.018378,0.026819,0.002706
2021-12-01,0.071289,0.013147,0.107007,0.005008,0.026160,0.078567,0.062683,0.071450,0.083497,0.082110,0.013147,-0.004449
2022-01-01,-0.057512,-0.096451,0.014391,0.173704,-0.000596,-0.075493,-0.045956,-0.060325,-0.072833,-0.032923,-0.082351,-0.017595
2022-02-01,-0.059812,-0.069602,-0.010852,0.019423,-0.026285,-0.039034,-0.071721,0.006485,-0.069150,-0.064110,-0.099373,-0.022719
2022-02-24,0.014099,0.021678,-0.020840,-0.001961,-0.010822,0.007628,0.013446,0.002122,0.017740,0.008924,0.041667,0.003275